spring:
 cloud:
   gateway:
     routes:
       - id: investor-service
         uri: lb://investor-service
         predicates:
           - Path=/investor/**
         filters:
           - AuthenticationFilter
           
       - id: retirement-service
         uri: lb://retirement-service
         predicates:
           - Path=/retirementAccount/**
         filters:
           - AuthenticationFilter   
           
           
       - id: savings-service
         uri: lb://savings-service
         predicates:
           - Path=/savings/**
         filters:
           - AuthenticationFilter
           
           
       - id: withdrawal-service
         uri: lb://withdrawal-service
         predicates:
           - Path=/withdrawals/**
         filters:
           - AuthenticationFilter         

       - id: identity-service
         uri: lb://IDENTITY-SERVICE
         predicates:
           - Path=/auth/**

 application:
   name: GATEWAY-SERVICE
  
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
      
server:
  port: 9191  
  
  
     
